In [1]:
import os
import sys
import pandas as pd

sys.path.append(os.path.abspath("../src"))

from cleaning.missing_handler import report_missing
from cleaning.clean_pipeline import run_cleaning_pipeline

In [5]:
df = pd.read_csv("../processed/cleaned/cleaned_data.csv")
df.head()

,_id,source,timestamp,name,city,country,categories,longitude,latitude,website,formatted_address,timestamp_year
0,69c1c9ec21c9fc4ece6b369d,geoapify_json,2026-03-24 00:17:00.235,dom oružanih snaga bih,sarajevo,bosnia and herzegovina,"activity, activity.community_center, building,...",18.424120,43.857283,http://www.mod.gov.ba/,"armed forces hall of bosnia and herzegovina, z...",2026
1,69c1c9ec21c9fc4ece6b369e,geoapify_json,2026-03-24 00:17:00.273,zajednički štab oružanih snaga bih,sarajevo,bosnia and herzegovina,"building, building.historic, building.military...",18.429970,43.856776,http://www.mod.gov.ba/,"joint staff of the armed forces of bih, bistri...",2026
2,69c1c9ec21c9fc4ece6b369f,geoapify_json,2026-03-24 00:17:00.274,gazi husrev-begov bezistan,sarajevo,bosnia and herzegovina,"building, building.commercial, building.histor...",18.428079,43.858747,unknown,"gazi husrev bey's bezistan, mudželiti mali, 71...",2026
3,69c1c9ec21c9fc4ece6b36a0,geoapify_json,2026-03-24 00:17:00.274,aškenaška sinagoga,sarajevo,bosnia and herzegovina,"building, building.historic, building.place_of...",18.425081,43.856311,unknown,"ashkenazi synagogue, hamdije kreševljakovića, ...",2026
4,69c1c9ec21c9fc4ece6b36a1,geoapify_json,2026-03-24 00:17:00.275,katedrala srca isusova,sarajevo,bosnia and herzegovina,"building, building.historic, building.place_of...",18.425363,43.859430,https://katedrala-sarajevo.com/,"sacred heart cathedral, trg fra grge martića, ...",2026

In [7]:
print("Original shape:", df.shape)

Original shape: (666, 12)

In [8]:
df.isna().sum()

_id                  0
source               0
timestamp            0
name                 0
city                 0
country              0
categories           0
longitude            0
latitude             0
website              0
formatted_address    0
timestamp_year       0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

_id                      str
source                   str
timestamp                str
name                     str
city                     str
country                  str
categories               str
longitude            float64
latitude             float64
website                  str
formatted_address        str
timestamp_year         int64
dtype: object

In [11]:
df.head(10)

,_id,source,timestamp,name,city,country,categories,longitude,latitude,website,formatted_address,timestamp_year
0,69c1c9ec21c9fc4ece6b369d,geoapify_json,2026-03-24 00:17:00.235,dom oružanih snaga bih,sarajevo,bosnia and herzegovina,"activity, activity.community_center, building,...",18.424120,43.857283,http://www.mod.gov.ba/,"armed forces hall of bosnia and herzegovina, z...",2026
1,69c1c9ec21c9fc4ece6b369e,geoapify_json,2026-03-24 00:17:00.273,zajednički štab oružanih snaga bih,sarajevo,bosnia and herzegovina,"building, building.historic, building.military...",18.429970,43.856776,http://www.mod.gov.ba/,"joint staff of the armed forces of bih, bistri...",2026
2,69c1c9ec21c9fc4ece6b369f,geoapify_json,2026-03-24 00:17:00.274,gazi husrev-begov bezistan,sarajevo,bosnia and herzegovina,"building, building.commercial, building.histor...",18.428079,43.858747,unknown,"gazi husrev bey's bezistan, mudželiti mali, 71...",2026
3,69c1c9ec21c9fc4ece6b36a0,geoapify_json,2026-03-24 00:17:00.274,aškenaška sinagoga,sarajevo,bosnia and herzegovina,"building, building.historic, building.place_of...",18.425081,43.856311,unknown,"ashkenazi synagogue, hamdije kreševljakovića, ...",2026
4,69c1c9ec21c9fc4ece6b36a1,geoapify_json,2026-03-24 00:17:00.275,katedrala srca isusova,sarajevo,bosnia and herzegovina,"building, building.historic, building.place_of...",18.425363,43.859430,https://katedrala-sarajevo.com/,"sacred heart cathedral, trg fra grge martića, ...",2026
5,69c1c9ec21c9fc4ece6b36a2,geoapify_json,2026-03-24 00:17:00.275,žuta tabija,sarajevo,bosnia and herzegovina,"tourism, tourism.attraction, tourism.attractio...",18.437724,43.861458,unknown,"žuta tabija, bijela česma, 71200 sarajevo, bos...",2026
6,69c1c9ec21c9fc4ece6b36a3,geoapify_json,2026-03-24 00:17:00.275,bijela tabija,sarajevo,bosnia and herzegovina,"building, building.historic, building.tourism,...",18.444490,43.859365,unknown,"bijela tabija, poddžebhana, 71200 sarajevo, bo...",2026
7,69c1c9ec21c9fc4ece6b36a4,geoapify_json,2026-03-24 00:17:00.276,stari grad vratnik,city of sarajevo,bosnia and herzegovina,"populated_place, populated_place.quarter, tour...",18.441291,43.863078,unknown,"stari grad vratnik, mz ""vratnik"", city of sara...",2026
8,69c1c9ec21c9fc4ece6b36a5,geoapify_json,2026-03-24 00:17:00.276,bistrik kula,sarajevo,bosnia and herzegovina,"building, building.historic, tourism, tourism....",18.438119,43.842187,unknown,"bistrik kula, old bobsleigh track, 71144 saraj...",2026
9,69c1c9ec21c9fc4ece6b36a6,geoapify_json,2026-03-24 00:17:00.277,trg oslobođenja - alija izetbegović,sarajevo,bosnia and herzegovina,"leisure, leisure.park, tourism, tourism.sights...",18.424207,43.858354,unknown,"trg oslobođenja - alija izetbegović, mz ""ferha...",2026

In [12]:
df.to_csv("../processed/cleaned/clean.csv", index=False)

In [13]:
missing_report = pd.DataFrame({
    "column": df.columns,
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
})

missing_report

                              column  missing_count  missing_percent
_id                              _id              0              0.0
source                        source              0              0.0
timestamp                  timestamp              0              0.0
name                            name              0              0.0
city                            city              0              0.0
country                      country              0              0.0
categories                categories              0              0.0
longitude                  longitude              0              0.0
latitude                    latitude              0              0.0
website                      website              0              0.0
formatted_address  formatted_address              0              0.0
timestamp_year        timestamp_year              0              0.0

In [14]:
missing_report.to_csv("../processed/cleaned/missing_report.csv", index=False)